import {AfterInsert, AfterRemove, AfterUpdate, Entity, Column, PrimaryGeneratedColumn } from "typeorm";
//This will be used in a repository. This will be our entity. Our database will create a table 
//using this entity. It will have id column, email column , password column. Each row will show
//an id, email and password informations.ID will be generated by database. For every input
//id will be increased by one. 


@Entity( )
export class User {

    @PrimaryGeneratedColumn()
    id: number 

    @Column()
    email: string

    @Column()
    password: string
   
    //After a new input inserted to db, console log this message.
    @AfterInsert()
    logInsert(){
        console.log("Inserted User with id", this.id)
    }

    //After a new input updated, console log this message.
    @AfterUpdate()
    logUpdate(){
        console.log("Updated User with id", this.id)
    }

    //After a new input remoced, console log this message.
    @AfterRemove()
    logRemove(){
        console.log("Removed User with id", this.id)
    }
}
